import { useEffect, useState } from "react";
import type { Layer, SoundtrackElement } from "./types";
import { LayerStrip } from "./component-LayerStrip";
import { SourceSelector, type Source } from "./component-SourceSelector";
import { apiFetch } from "./api";
interface SearchApiLayer{id:number|string;name:string;license:string;commerciallySafe:boolean;durationSeconds:number;previewUrl?:string;audioUrl?:string;freesoundUrl?:string;tags?:string[]}
const ENDPOINTS:Record<Extract<Source,"freesound"|"soundly">,string>={freesound:"/api/search/freesound",soundly:"/api/search/soundly"};
export function SoundtrackPanel({elementId,label,hint,query,layers,onLayersChange}:{elementId:SoundtrackElement;label:string;hint:string;query:string;layers:Layer[];onLayersChange:(l:Layer[])=>void}){
 const [search,setSearch]=useState(query);const [source,setSource]=useState<Source>("freesound");const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);useEffect(()=>setSearch(query),[query]);
 async function handleSearch(){if(!search.trim())return;setLoading(true);setError(null);try{if(source==="generado")throw new Error("Generado todavía no está conectado.");const p=new URLSearchParams({query:search.trim(),element:elementId});const r=await apiFetch(`${ENDPOINTS[source]}?${p.toString()}`);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??`error ${r.status}`);const incoming:Layer[]=(Array.isArray(d.results)?d.results:[]).map((x:SearchApiLayer)=>({id:`${source}-${x.id}`,element:elementId,source:source==="freesound"?"freesound":"soundly",name:x.name,license:x.license,commerciallySafe:x.commerciallySafe,durationSeconds:x.durationSeconds,audioUrl:x.previewUrl??x.audioUrl??"",freesoundUrl:x.freesoundUrl,tags:x.tags,gainDb:0,pan:0,muted:false,solo:false}));const ids=new Set(layers.map(l=>l.id));onLayersChange([...layers,...incoming.filter(l=>!ids.has(l.id))])}catch(e){setError(e instanceof Error?e.message:"no se pudo buscar")}finally{setLoading(false)}}
 function updateLayer(id:string,patch:Partial<Layer>){onLayersChange(layers.map(l=>l.id===id?{...l,...patch}:l))}function removeLayer(id:string){onLayersChange(layers.filter(l=>l.id!==id))}
 return <section className="panel" aria-labelledby={`panel-${elementId}`}><header className="panel__header"><h2 id={`panel-${elementId}`}>{label}</h2><span className="panel__hint">{hint}</span></header><SourceSelector value={source} onChange={setSource}/><div className="panel__search"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&handleSearch()} placeholder="describí el sonido..."/><button onClick={handleSearch} disabled={loading}>{loading?"...":"buscar"}</button></div>{error&&<p className="panel__error">{error}</p>}<div className="panel__layers">{layers.length===0&&!loading&&<p className="panel__empty">sin capas todavía</p>}{layers.map(layer=><LayerStrip key={layer.id} layer={layer} onChange={patch=>updateLayer(layer.id,patch)} onRemove={()=>removeLayer(layer.id)}/>)}</div></section>
}
