import { useState } from "react";
import type { Certainty, ProposalCategory, SceneAnalysis, SoundDesignProposal, SoundProposal } from "./types";
import { apiFetch } from "./api";
const CATEGORY_LABEL:Record<ProposalCategory,string>={ambientes:"Ambientes",efectos:"Efectos",foley:"Foley",dialogos:"Diálogos"};
const CATEGORIES:ProposalCategory[]=["ambientes","efectos","foley","dialogos"];
function emptyProposal(category:ProposalCategory):SoundProposal{return{id:`${category}-manual-${crypto.randomUUID()}`,category,description:"",rationale:"",certainty:"possible"}}
export function SoundDesignProposalPanel({analysis}:{analysis:SceneAnalysis|null}){
 const [proposal,setProposal]=useState<SoundDesignProposal|null>(null); const [generating,setGenerating]=useState(false); const [error,setError]=useState<string|null>(null);
 async function handleGenerate(){if(!analysis)return;setGenerating(true);setError(null);try{const r=await apiFetch("/api/design/proposal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysis})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??`error ${r.status}`);setProposal(d as SoundDesignProposal)}catch(e){setError(e instanceof Error?e.message:"no se pudo generar la propuesta")}finally{setGenerating(false)}}
 function updateItem(c:ProposalCategory,id:string,patch:Partial<SoundProposal>){setProposal(p=>p?{...p,[c]:p[c].map(x=>x.id===id?{...x,...patch}:x)}:p)}
 function removeItem(c:ProposalCategory,id:string){setProposal(p=>p?{...p,[c]:p[c].filter(x=>x.id!==id)}:p)}
 function addItem(c:ProposalCategory){setProposal(p=>{const base=p??{ambientes:[],efectos:[],foley:[],dialogos:[]};return{...base,[c]:[...base[c],emptyProposal(c)]}})}
 if(!analysis)return <div className="proposal-panel"><p className="panel__empty">Analizá un fotograma para generar una propuesta.</p></div>;
 return <div className="proposal-panel"><button className="proposal-panel__generate-btn" onClick={handleGenerate} disabled={generating}>{generating?"pensando el diseño sonoro...":proposal?"volver a generar":"generar propuesta de diseño sonoro"}</button>{error&&<p className="proposal-panel__error">{error}</p>}{proposal&&<div className="proposal-panel__categories">{CATEGORIES.map(c=><div key={c} className="proposal-panel__category"><div className="proposal-panel__category-title">{CATEGORY_LABEL[c]}</div>{proposal[c].length===0&&<p className="proposal-panel__empty">sin propuestas todavía</p>}{proposal[c].map(item=><div key={item.id} className="proposal-item"><div className="proposal-item__row"><input className="proposal-item__description" value={item.description} placeholder="descripción del sonido" onChange={e=>updateItem(c,item.id,{description:e.target.value})}/><select className={`proposal-item__certainty certainty-${item.certainty}`} value={item.certainty} onChange={e=>updateItem(c,item.id,{certainty:e.target.value as Certainty})}><option value="observed">observado</option><option value="probable">probable</option><option value="possible">posible</option></select><button className="proposal-item__remove" onClick={()=>removeItem(c,item.id)} aria-label="Eliminar propuesta">×</button></div><input className="proposal-item__rationale" value={item.rationale} placeholder="por qué encaja en la escena..." onChange={e=>updateItem(c,item.id,{rationale:e.target.value})}/></div>)}<button className="proposal-panel__add-btn" onClick={()=>addItem(c)}>+ agregar propuesta</button></div>)}</div>}</div>;
}
