import { coerceCertainty, type Certainty, type SceneAnalysis } from "./provider-vision.ts";
const MODEL="qwen/qwen3.6-27b"; const ENDPOINT="https://api.groq.com/openai/v1/chat/completions"; const MAX=6;
export type ProposalCategory="ambientes"|"efectos"|"foley"|"dialogos";
export interface SoundProposal{id:string;category:ProposalCategory;description:string;rationale:string;certainty:Certainty;}
export interface SoundDesignProposal{ambientes:SoundProposal[];efectos:SoundProposal[];foley:SoundProposal[];dialogos:SoundProposal[];}
export interface GenerateProposalParams{analysis:SceneAnalysis;apiKey:string;}
const PROMPT=`Sos un diseñador de sonido profesional para cine y video. A partir de este análisis, proponé una selección pequeña y útil de sonidos, no una lista exhaustiva. Máximo ${MAX} por categoría, idealmente 2 a 4. Categorías: ambientes (fondo continuo), efectos (puntuales), foley (acciones y superficies), dialogos (voces o ausencia evidente). Cada propuesta debe tener description, rationale y certainty: observed, probable o possible. Nunca uses observed para una idea especulativa. Todo en español. Respondé solo JSON con arrays ambientes, efectos, foley y dialogos.`;
function coerce(v:any,c:ProposalCategory,i:number):SoundProposal|null{const d=typeof v?.description==="string"?v.description.trim():"";if(!d)return null;return{id:`${c}-${i}`,category:c,description:d,rationale:typeof v?.rationale==="string"?v.rationale.trim():"",certainty:coerceCertainty(v?.certainty)}}
function arr(v:any,c:ProposalCategory){return(Array.isArray(v)?v:[]).map((x,i)=>coerce(x,c,i)).filter((x):x is SoundProposal=>!!x).slice(0,MAX)}
export function normalizeProposal(raw:any):SoundDesignProposal{return{ambientes:arr(raw?.ambientes,"ambientes"),efectos:arr(raw?.efectos,"efectos"),foley:arr(raw?.foley,"foley"),dialogos:arr(raw?.dialogos,"dialogos")}}
export async function generateSoundDesignProposal({analysis,apiKey}:GenerateProposalParams):Promise<SoundDesignProposal>{const res=await fetch(ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:MODEL,messages:[{role:"user",content:PROMPT+"\n\nANÁLISIS:\n"+JSON.stringify(analysis)}],temperature:0.6,max_completion_tokens:2048,response_format:{type:"json_object"}})});if(!res.ok){const t=await res.text().catch(()=>"");throw new Error(`Groq proposal request failed (${res.status}): ${t.slice(0,300)}`)}const data:any=await res.json();const content=data?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("Groq no devolvió contenido de propuesta");let parsed:any;try{parsed=JSON.parse(content)}catch{throw new Error("La propuesta no llegó en JSON válido")}return normalizeProposal(parsed)}
