const VISION_MODEL = "qwen/qwen3.6-27b";
const GROQ_CHAT_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions";
export type Certainty="observed"|"probable"|"possible";
export interface SoundCue{text:string; certainty:Certainty;}
export interface SceneAnalysis{sceneDescription:string;place:SoundCue;indoorOutdoor:SoundCue;timeOfDay:SoundCue;weather:SoundCue;materialsAndSurfaces:SoundCue[];humanPresence:SoundCue;potentialSoundSources:SoundCue[];observedActions:SoundCue[];offScreenSources:SoundCue[];ambience:SoundCue[];effects:SoundCue[];foley:SoundCue[];dialogue:SoundCue[];narrativeIdeas:SoundCue[];}
export interface AnalyzeFrameParams{image:string;apiKey:string;}
const PROMPT=`Sos un asistente de diseño sonoro para cine y video. Mirá el fotograma y analizalo específicamente para diseñar sonido, no como una descripción visual genérica. Para cada afirmación usá certeza observed, probable o possible. observed = visible directamente; probable = inferencia razonable; possible = posibilidad creativa. Nunca presentes una posibilidad como hecho. Identificá lugar, interior/exterior, momento del día, clima, materiales y superficies, presencia humana, fuentes sonoras, acciones, fuera de campo y propuestas de ambiente, efectos, foley, diálogo e ideas narrativas. Priorizá información acústicamente útil y no inventes datos innecesarios. Todo en español. Respondé solo JSON con las claves sceneDescription, place, indoorOutdoor, timeOfDay, weather, materialsAndSurfaces, humanPresence, potentialSoundSources, observedActions, offScreenSources, ambience, effects, foley, dialogue, narrativeIdeas.`;
export function coerceCertainty(v:unknown):Certainty{return v==="observed"||v==="probable"||v==="possible"?v:"possible";}
export function coerceCue(v:any):SoundCue{return{text:typeof v?.text==="string"?v.text.trim():"",certainty:coerceCertainty(v?.certainty)}}
export function coerceCueArray(v:any):SoundCue[]{return Array.isArray(v)?v.map(coerceCue).filter(c=>c.text):[]}
export function normalizeAnalysis(raw:any):SceneAnalysis{return{sceneDescription:typeof raw?.sceneDescription==="string"?raw.sceneDescription.trim():"",place:coerceCue(raw?.place),indoorOutdoor:coerceCue(raw?.indoorOutdoor),timeOfDay:coerceCue(raw?.timeOfDay),weather:coerceCue(raw?.weather),materialsAndSurfaces:coerceCueArray(raw?.materialsAndSurfaces),humanPresence:coerceCue(raw?.humanPresence),potentialSoundSources:coerceCueArray(raw?.potentialSoundSources),observedActions:coerceCueArray(raw?.observedActions),offScreenSources:coerceCueArray(raw?.offScreenSources),ambience:coerceCueArray(raw?.ambience),effects:coerceCueArray(raw?.effects),foley:coerceCueArray(raw?.foley),dialogue:coerceCueArray(raw?.dialogue),narrativeIdeas:coerceCueArray(raw?.narrativeIdeas)};}
export async function analyzeFrame({image,apiKey}:AnalyzeFrameParams):Promise<SceneAnalysis>{const res=await fetch(GROQ_CHAT_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey}`},body:JSON.stringify({model:VISION_MODEL,messages:[{role:"user",content:[{type:"text",text:PROMPT},{type:"image_url",image_url:{url:image}}]}],temperature:0.4,max_completion_tokens:2048,response_format:{type:"json_object"}})});if(!res.ok){const t=await res.text().catch(()=>"");throw new Error(`Groq vision request failed (${res.status}): ${t.slice(0,300)}`)}const data:any=await res.json();const content=data?.choices?.[0]?.message?.content;if(typeof content!=="string")throw new Error("Groq no devolvió contenido de análisis");let parsed:any;try{parsed=JSON.parse(content)}catch{throw new Error("El análisis no llegó en JSON válido")}return normalizeAnalysis(parsed)}
